name: Build and push Docker image

on:
    push:
        tags:
            - 'v*'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4

            -   name: Log in to GHCR
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: ghcr.io/doguabaris/corev-cli:latest
                    labels: |
                        org.opencontainers.image.source=https://github.com/doguabaris/corev-cli
                        org.opencontainers.image.description=Minimal CLI to manage config versions
                        org.opencontainers.image.licenses=MIT
